# Generated by Django 3.2.4 on 2021-06-11 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(db_column='USERNAME', max_length=100, unique=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='FIRST_NAME', max_length=60)),
                ('last_name', models.CharField(db_column='LAST_NAME', max_length=60)),
                ('password', models.CharField(db_column='PASSWORD', max_length=20)),
                ('gender', models.IntegerField(db_column='GENDER')),
                ('date_of_birth', models.DateTimeField(blank=True, db_column='DATE_OF_BIRTH', null=True)),
                ('mobile_number', models.CharField(blank=True, db_column='MOBILE_NUMBER', max_length=20, null=True)),
                ('address_1', models.CharField(db_column='ADDRESS_1', max_length=100)),
                ('address_2', models.CharField(blank=True, db_column='ADDRESS_2', max_length=100, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('project_name', models.CharField(db_column='PROJECT_NAME', max_length=60)),
                ('project_details', models.TextField(blank=True, db_column='PROJECT_DETAILS', null=True)),
                ('project_start_date', models.DateTimeField(db_column='PROJECT_START_DATE')),
                ('project_expected_end_date', models.DateTimeField(blank=True, db_column='PROJECT_EXPECTED_END_DATE', null=True)),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectProgressStatus',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('status', models.CharField(db_column='STATUS', max_length=45)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=255, null=True)),
            ],
            options={
                'db_table': 'project_progress_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('role_name', models.CharField(db_column='ROLE_NAME', max_length=45)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
    ]
